
dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: preview
  name: nuxeo-notification-stream
  repository: file://../nuxeo-notification-stream
